language: node_js
dist: trusty
sudo: false
node_js: 
  - "8"

cache:
  directories:
    - node_modules
  
matrix:
  fast_finish: true

install:
  - npm install

script:
  - ng build --prod

deploy: 
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master